### ISSUE TITLE
Release Notes + releases on Github

### ISSUE THREAD

**Issue by valliman** [Mobicents/jain-sip#37]
Hi,

it seems that you guys are heavily developing again for JAIN-SIP. I would really appreciate it if you could provide some sort of release notes for the releases pushed to maven central? (Or maybe there are those and I just missed them).

Additionally why not also add the releases on github.

BR

**Comment by deruelle** [comment]
There aren't been any major changes for a while. We use continuous delivery, see https://mobicents.ci.cloudbees.com/job/JAIN-SIP/ for regular patch updates which deploy automatically to sonatype which synchronizes to maven central. 
We assumed everyone would be consuming through maven, which is why we avoid duplicating the releases to github so far. Maybe when there is a major change we will cut a release. Feel free to comment.
